import person1 from "../../../../assets/person1.jpg"
import person2 from "../../../../assets/person2.jpg"
import person3 from "../../../../assets/person3.jpg"
import person4 from "../../../../assets/person4.jpg"
import makeup from "../../../../assets/makeup.jpg"
import coloring from "../../../../assets/coloring.jpg"



export const ourTeam = [
    {
        id: 1, name: 'Dona', lastName: 'Vazen', role: 'Hair Colorist',
        smallDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet ',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .',
        image: person1,
        instagram: 'https://wwww.instagram.com'
    },
    {
        id: 2, name: 'Ellen', lastName: 'Girri', role: 'Make Up',
        smallDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet ',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .',
        image: person4,
        instagram: 'https://wwww.instagram.com'
    },
    {
        id: 3, name: 'Njteh', lastName: 'Carlos', role: 'Hair Colorist',
        smallDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet ',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .',
        image: person2,
        instagram: 'https://wwww.instagram.com'
    },
    {
        id: 4, name: 'Siri', lastName: 'Iosan', role: 'Hair Brusher',
        smallDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet ',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .',
        image: person3,
        instagram: 'https://wwww.instagram.com'
    },
    {
        id: 5, name: 'Jackob', lastName: 'Ville', role: 'Hair Colorist',
        smallDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet ',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .',
        image: coloring,
        instagram: 'https://wwww.instagram.com'
    },
    {
        id: 6, name: 'Maria', lastName: 'Gusto', role: 'Make Up',
        smallDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet ',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum qui quidem, aliquam iure praesentium neque architecto perspiciatis nulla numquam .',
        image: makeup,
        instagram: 'https://wwww.instagram.com'
    },
]
